ONOS_IP = 'localhost'
ONOS_PORT = 8181
ONOS_USER = 'karaf'
ONOS_PASS = 'karaf'

EDGE_BANDWIDTH_LIMIT = 1e6 # unit: Kbps
LINK_BANDWIDTH_LIMIT = 10e3 # unit: Kbps
BANDWIDTH_THRESHOLD = 0.9

POLLING_INTERVAL = 5
STATISTICS_INTERVAL = 5
